import GlobalState from "@/Context";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/Components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <Navbar></Navbar>
          <main className=" flex min-h-screen flex-col mt-[90px]">{children}</main>
        </GlobalState>
      </body>
    </html>
  );
}
